export type {
  Faculty,
  FacultyProfile,
  FacultyQualification,
  FacultyExperience,
  FacultyCourseAssignment,
  FacultyCreateData,
  FacultyUpdateData,
  FacultyProfileCreateData,
  FacultyProfileUpdateData,
  FacultyCourseAssignmentCreateData,
  FacultyCourseAssignmentUpdateData,
  FacultyListParams,
  EmploymentType,
  EmploymentStatus,
  FacultyGender,
  FacultyBloodGroup,
} from './faculty'
