# Generated by Django 6.1.1 on 2026-10-02 10:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0003_alter_regulation_options_alter_course_regulation'),
        ('students', '0004_studentprofile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('exam_type', models.CharField(choices=[('MID_I', 'Mid-I'), ('MID_II', 'Mid-II'), ('SEMESTER', 'Semester End'), ('LAB', 'Laboratory'), ('INTERNAL', 'Internal Assessment')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('max_marks', models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(1)])),
                ('is_published', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exams', to='academics.semester')),
            ],
            options={
                'ordering': ['-start_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StudentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marks', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('grade', models.CharField(blank=True, max_length=5)),
                ('grade_point', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('status', models.CharField(choices=[('PASS', 'Pass'), ('FAIL', 'Fail'), ('ABSENT', 'Absent'), ('WITHHELD', 'Withheld')], default='PASS', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_results', to='academics.course')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_results', to='examinations.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_results', to='students.student')),
            ],
            options={
                'ordering': ['course__code'],
            },
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.UniqueConstraint(fields=('name', 'semester'), name='unique_exam_per_semester'),
        ),
        migrations.AddConstraint(
            model_name='studentresult',
            constraint=models.UniqueConstraint(fields=('student', 'exam', 'course'), name='unique_student_exam_course_result'),
        ),
    ]
