# Generated by Django 6.1.1 on 2026-09-18 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otprecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otprecord',
            options={},
        ),
        migrations.AddField(
            model_name='otprecord',
            name='challenge_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='otprecord',
            name='challenge_token_hash',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_student_registered',
            field=models.BooleanField(default=False),
        ),
    ]
