# Generated by Django 6.1.1 on 2026-09-08 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_alter_course_code_regulation_course_regulation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regulation',
            options={'ordering': ['-start_year', 'code']},
        ),
        migrations.AlterField(
            model_name='course',
            name='regulation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='academics.regulation'),
        ),
    ]
