import {useState} from 'react'
import {useCurrentUser} from '../../auth/useCurrentUser'
import {useCourseOfferings} from '../../academics/hooks'
import {useAssignments,useAssignmentSubmissions,useCreateAssignment,useCreateAssignmentSubmission,useDeleteAssignment,useUpdateAssignment,useUpdateAssignmentSubmission} from '../hooks/useAssignments'
import type {AssignmentStatus} from '../types/assignments'

export default function AssignmentsPage(){
 const {data:user}=useCurrentUser();const roles=user?.roles??[];const isStudent=roles.includes('STUDENT')&&!roles.includes('ADMIN')&&!roles.includes('HOD')
 const [showForm,setShowForm]=useState(false);const [selected,setSelected]=useState<number|null>(null);const [error,setError]=useState('')
 const assignments=useAssignments();const offerings=useCourseOfferings({status:'OPEN'});const create=useCreateAssignment();const update=useUpdateAssignment();const remove=useDeleteAssignment();const submit=useCreateAssignmentSubmission()
 const [form,setForm]=useState({offering:'',title:'',description:'',due_date:'',max_marks:'10',status:'DRAFT' as AssignmentStatus,attachment:null as File|null});const [answer,setAnswer]=useState('');const [file,setFile]=useState<File|null>(null)
 const save=()=>{setError('');if(!form.offering||!form.title||!form.due_date)return setError('Course offering, title and due date are required.');create.mutate({offering:Number(form.offering),title:form.title,description:form.description,due_date:new Date(form.due_date).toISOString(),max_marks:Number(form.max_marks),status:form.status,attachment:form.attachment},{onSuccess:()=>setShowForm(false),onError:()=>setError('Unable to save assignment.')})}
 return <div className="space-y-6"><header className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-sm font-semibold uppercase tracking-wider text-blue-600">Academic Operations</p><h1 className="mt-1 text-3xl font-bold text-slate-950">Assignments</h1><p className="mt-2 text-sm text-slate-500">Manage course work, submissions and grading from one place.</p></div>{!isStudent&&<button onClick={()=>setShowForm(!showForm)} className="rounded-xl bg-slate-950 px-5 py-3 text-sm font-semibold text-white">{showForm?'Close editor':'+ Create assignment'}</button>}</header>
 {error&&<div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}
 {!isStudent&&showForm&&<section className="rounded-2xl border bg-white p-6 shadow-sm"><h2 className="text-lg font-semibold">Create assignment</h2><div className="mt-5 grid gap-4 md:grid-cols-2"><label><span className="mb-1 block text-sm font-medium">Course offering</span><select className="w-full rounded-xl border p-3" value={form.offering} onChange={e=>setForm({...form,offering:e.target.value})}><option value="">Select offering</option>{(offerings.data?.results??[]).map(o=><option key={o.id} value={o.id}>{o.course_code} - Section {o.section}</option>)}</select></label><label><span className="mb-1 block text-sm font-medium">Title</span><input className="w-full rounded-xl border p-3" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label><span className="mb-1 block text-sm font-medium">Due date</span><input type="datetime-local" className="w-full rounded-xl border p-3" value={form.due_date} onChange={e=>setForm({...form,due_date:e.target.value})}/></label><label><span className="mb-1 block text-sm font-medium">Maximum marks</span><input type="number" min="1" className="w-full rounded-xl border p-3" value={form.max_marks} onChange={e=>setForm({...form,max_marks:e.target.value})}/></label><label className="md:col-span-2"><span className="mb-1 block text-sm font-medium">Description</span><textarea className="w-full rounded-xl border p-3" rows={4} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label><span className="mb-1 block text-sm font-medium">Status</span><select className="w-full rounded-xl border p-3" value={form.status} onChange={e=>setForm({...form,status:e.target.value as AssignmentStatus})}><option>DRAFT</option><option>PUBLISHED</option></select></label><label><span className="mb-1 block text-sm font-medium">Attachment</span><input type="file" className="w-full rounded-xl border p-3" onChange={e=>setForm({...form,attachment:e.target.files?.[0]??null})}/></label></div><button onClick={save} className="mt-5 rounded-xl bg-blue-600 px-5 py-3 text-sm font-semibold text-white">Save assignment</button></section>}
 <section className="grid gap-4 lg:grid-cols-2">{(assignments.data?.results??[]).map(a=><article key={a.id} className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex justify-between gap-3"><div><p className="text-xs font-bold uppercase text-blue-600">{a.course_code} · Section {a.section}</p><h2 className="mt-1 text-xl font-bold">{a.title}</h2><p className="mt-2 text-sm text-slate-500">{a.description||'No description provided.'}</p></div><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold">{a.status}</span></div><div className="mt-4 grid grid-cols-3 gap-3 text-xs"><Metric label="Due" value={new Date(a.due_date).toLocaleString()}/><Metric label="Marks" value={String(a.max_marks)}/><Metric label="Submissions" value={String(a.submission_count)}/></div>{a.attachment&&<a className="mt-4 inline-block text-sm font-semibold text-blue-600" href={a.attachment} target="_blank">View attachment</a>}<div className="mt-5 flex flex-wrap gap-2">{isStudent&&a.status==='PUBLISHED'&&<button onClick={()=>setSelected(selected===a.id?null:a.id)} className="rounded-lg bg-blue-600 px-4 py-2 text-xs font-semibold text-white">Submit work</button>}{!isStudent&&a.status==='DRAFT'&&<button onClick={()=>update.mutate({id:a.id,data:{status:'PUBLISHED'}})} className="rounded-lg bg-emerald-600 px-4 py-2 text-xs font-semibold text-white">Publish</button>}{!isStudent&&<button onClick={()=>setSelected(selected===a.id?null:a.id)} className="rounded-lg border px-4 py-2 text-xs font-semibold">Submissions</button>}{!isStudent&&<button onClick={()=>remove.mutate(a.id)} className="rounded-lg border border-red-200 px-4 py-2 text-xs font-semibold text-red-600">Delete</button>}</div>{isStudent&&selected===a.id&&<div className="mt-4 rounded-xl bg-slate-50 p-4"><textarea className="w-full rounded-lg border p-3" rows={4} placeholder="Write your answer..." value={answer} onChange={e=>setAnswer(e.target.value)}/><input type="file" className="mt-3" onChange={e=>setFile(e.target.files?.[0]??null)}/><button onClick={()=>submit.mutate({assignment:a.id,answer_text:answer,file})} className="mt-3 rounded-lg bg-slate-950 px-4 py-2 text-sm font-semibold text-white">Submit assignment</button></div>}{!isStudent&&selected===a.id&&<SubmissionPanel assignment={a.id}/>}</article>)}</section></div>
}
function SubmissionPanel({assignment}:{assignment:number}){const {data}=useAssignmentSubmissions({assignment});const grade=useUpdateAssignmentSubmission();return <div className="mt-4 space-y-3 rounded-xl bg-slate-50 p-4">{(data?.results??[]).map(s=><div key={s.id} className="rounded-lg border bg-white p-3"><p className="text-sm font-semibold">{s.student_name} · {s.student_id}</p><p className="text-xs text-slate-500">{new Date(s.submitted_at).toLocaleString()}</p>{s.file&&<a href={s.file} target="_blank" className="mt-2 block text-xs font-semibold text-blue-600">Open submission</a>}<p className="mt-2 text-sm">{s.answer_text||'No text answer.'}</p><div className="mt-3 flex gap-2"><input id={'marks-'+s.id} type="number" min="0" defaultValue={s.marks??''} className="w-24 rounded-lg border p-2 text-sm"/><input id={'feedback-'+s.id} defaultValue={s.feedback} placeholder="Feedback" className="flex-1 rounded-lg border p-2 text-sm"/><button onClick={()=>{const m=(document.getElementById('marks-'+s.id) as HTMLInputElement).value;const f=(document.getElementById('feedback-'+s.id) as HTMLInputElement).value;grade.mutate({id:s.id,data:{marks:m?Number(m):null,feedback:f,status:'GRADED'}})}} className="rounded-lg bg-blue-600 px-3 py-2 text-xs font-semibold text-white">Grade</button></div></div>)}</div>}
function Metric({label,value}:{label:string;value:string}){return <div className="rounded-lg bg-slate-50 p-2"><p className="text-slate-400">{label}</p><p className="font-semibold">{value}</p></div>}
