# Generated by Django 6.1.1 on 2026-09-19 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='institutional_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
