# Generated by Django 6.1.1 on 2026-09-24 18:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_regulation_options_alter_course_regulation'),
        ('faculty', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='FacultyQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('degree', models.CharField(max_length=150)),
                ('specialization', models.CharField(blank=True, max_length=200)),
                ('institution', models.CharField(max_length=200)),
                ('university', models.CharField(blank=True, max_length=200)),
                ('year_of_passing', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2100)])),
                ('grade_or_percentage', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['-year_of_passing'],
            },
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={'ordering': ['faculty_id']},
        ),
        migrations.AlterModelOptions(
            name='facultycourseassignment',
            options={'ordering': ['-assigned_date', 'faculty', 'course']},
        ),
        migrations.AlterModelOptions(
            name='facultyprofile',
            options={'ordering': ['first_name', 'last_name']},
        ),
        migrations.RemoveConstraint(
            model_name='facultycourseassignment',
            name='unique_faculty_course_assignment',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='employment_status',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='is_active',
        ),
        migrations.AddField(
            model_name='faculty',
            name='employment_type',
            field=models.CharField(choices=[('PERMANENT', 'Permanent'), ('CONTRACT', 'Contract'), ('GUEST', 'Guest'), ('VISITING', 'Visiting')], default='PERMANENT', max_length=20),
        ),
        migrations.AddField(
            model_name='faculty',
            name='faculty_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ON_LEAVE', 'On Leave'), ('RETIRED', 'Retired'), ('RESIGNED', 'Resigned')], default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='facultycourseassignment',
            name='assigned_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facultycourseassignment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='facultycourseassignment',
            name='section',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='institutional_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='personal_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='faculty/photos/'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='faculty', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='facultycourseassignment',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_assignments', to='faculty.faculty'),
        ),
        migrations.AlterField(
            model_name='facultyprofile',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='facultyprofile',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='facultyprofile',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AddConstraint(
            model_name='facultycourseassignment',
            constraint=models.UniqueConstraint(fields=('faculty', 'course', 'academic_year', 'semester', 'section'), name='unique_faculty_course_assignment'),
        ),
        migrations.AddField(
            model_name='facultyexperience',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='faculty.faculty'),
        ),
        migrations.AddField(
            model_name='facultyqualification',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='faculty.faculty'),
        ),
        migrations.RemoveField(
            model_name='facultycourseassignment',
            name='role',
        ),
    ]
