# Generated by Django 6.1.1 on 2026-09-24 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_facultyexperience_facultyqualification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='faculty_id',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='facultycourseassignment',
            name='assigned_date',
            field=models.DateField(),
        ),
    ]
